name: 刷步数

on:
  # schedule:
  #   - cron: '21 1,4,7,10,12,14,23 * * *'
  # 开启 API 调用触发，并定义需要接收的参数
  workflow_dispatch:
    inputs:
      account:
        description: '小米运动账号 (若为空则默认使用原配置)'
        required: false
        type: string
      password:
        description: '小米运动密码'
        required: false
        type: string
      steps:
        description: '目标步数'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
          
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          
      - name: 开始
        env:
          CONFIG: ${{ secrets.CONFIG }}
          AES_KEY: ${{ secrets.AES_KEY }}
          # 将 API 传进来的参数注入为环境变量
          MI_USER: ${{ inputs.account }}
          MI_PWD: ${{ inputs.password }}
          MI_STEP: ${{ inputs.steps }}
        run: |
          pip3 install requests pytz pycryptodome
          python3 main.py

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          # 加入 || echo "No changes to commit" 防止因为没有文件修改导致运行报错
          git commit -m "persist tokens trigger by ${{ github.event_name }}" || echo "No changes to commit"
          git push origin master
